export const menteeListInfo = [
  {
    id: 1,
    hrmId: "2601",
    employeeName: "Divyanshu Rana",
    position: "Intern",
    joiningDate: "06.09.2022",
    currentCourses: ["UI/UX Design", "HTML/CSS", "JavaScript", "React"],
  },
  {
    id: 2,
    hrmId: "2602",
    employeeName: "Hemendra Singh",
    position: "Intern",
    joiningDate: "06.09.2022",
    currentCourses: ["HTML/CSS", "JavaScript", "React", "Angular", "Node.js"],
  },
  {
    id: 3,
    hrmId: "2603",
    employeeName: "Abhishek Upadhaya",
    position: "Intern",
    joiningDate: "06.09.2022",
    currentCourses: ["HTML/CSS", "JavaScript", "React"],
  },
  {
    id: 4,
    hrmId: "2604",
    employeeName: "Muskan Chopra",
    position: "Intern",
    joiningDate: "06.09.2022",
    currentCourses: ["HTML/CSS", "JavaScript", "React"],
  },
  {
    id: 5,
    hrmId: "2605",
    employeeName: "Shreyansh Kothari",
    position: "Intern",
    joiningDate: "11.10.2021",
    currentCourses: [
      "UI/UX Design",
      "UI/UX Laws",
      "HTML/CSS",
      "JavaScript",
      "React",
      "Angular",
    ],
  },
  {
    id: 6,
    hrmId: "2606",
    employeeName: "Hemant Patel",
    position: "Associate",
    joiningDate: "16.03.2021",
    currentCourses: ["JavaScript", "React", "Node.js", ".net"],
  },
  {
    id: 7,
    hrmId: "2607",
    employeeName: "Nirmal Sir",
    position: "Associate consultant",
    joiningDate: "23.07.2021",
    currentCourses: [
      "Flutter",
      "Dart",
      "Node.js",
      "JavaScript",
      "React",
      "Angular",
    ],
  },
  {
    id: 8,
    hrmId: "2608",
    employeeName: "Anmol Sir",
    position: "Associate",
    joiningDate: "07.10.2021",
    currentCourses: ["HTML/CSS", "JavaScript", "React", "Node.js"],
  },
  {
    id: 9,
    hrmId: "2609",
    employeeName: "Rinkle Sir",
    position: "Associate",
    joiningDate: "15.08.2021",
    currentCourses: ["React", "HTML/CSS", "JavaScript", "Angular", ".net"],
  },
  {
    id: 10,
    hrmId: "2610",
    employeeName: "Himanshu Sir",
    position: "Associate",
    joiningDate: "23.12.2022",
    currentCourses: ["Angular", "JavaScript", "HTML/CSS", "React"],
  },
  {
    id: 11,
    hrmId: "2611",
    employeeName: "Stuti Khandelwal",
    position: "Junior Assosiate",
    joiningDate: "11.10.2022",
    currentCourses: [
      "Pyhton",
      "Virtualization",
      "Azure",
      "Data Analytics",
      "sql",
    ],
  },
  {
    id: 12,
    hrmId: "2612",
    employeeName: "Sujit Jha",
    position: "Intern",
    joiningDate: "17.03.2022",
    currentCourses: ["HTML/CSS", "JavaScript", "Node.js", "sql", "MongoDB"],
  },
];
