export const userActions = {
    ENROLLED_COURSE_DATA_INFO: 'ENROLLED_COURSE_DATA_INFO',
    ENROLLED_COURSE_LIST:"ENROLLED_COURSE_LIST",
    GET_PROFILE_DATA:"GET_PROFILE_DATA",
    GET_USER_DASHBOARD:"GET_USER_DASHBOARD"
}





