const Data = [
    {
        code :2601,
        coursename : "Node.js",
        department : "App Development",
        technology : "Node.js",
        duration : "3 weeks",
        modules : 12,
        complexity : "Intermediate",
        latestModifyBy : "Madhuri Kailash",
        latestModifyOn : "01/11/2022",
        addedBy : "Nirmal Kukna"
    },
    {
        code :2602,
        coursename : "React.js",
        department : "Chat Bot",
        technology : "React.js",
        duration : "2 weeks",
        modules : 20,
        complexity : "Begginer",
        latestModifyBy : "Naira Jain",
        latestModifyOn : "11/04/2022",
        addedBy : "Gaurav Sharma"
    },
    {
        code :2603,
        coursename : "Business",
        department : "Business Anaylist",
        technology : "Node.js",
        duration : "4 weeks",
        modules : 19,
        complexity : "Beginner",
        latestModifyBy : "Krupa Jitendara",
        latestModifyOn : "02/02/2022",
        addedBy : "Ishan Jain"
    },
    {
        code :2604,
        coursename : "HR",
        department : "HUman Resource",
        technology : "React.js",
        duration : "2 weeks",
        modules : 17,
        complexity : "Intermediate",
        latestModifyBy : "Khushu Kumari",
        latestModifyOn : "01/01/2022",
        addedBy : "Anmol Rathore"
    },
    {
        code :2605,
        coursename : "Node.js",
        department : "Big-Data",
        technology : "Node.js",
        duration : "3 weeks",
        modules : 13,
        complexity : "Advance",
        latestModifyBy : "Kanika Maan",
        latestModifyOn : "23/10/2022",
        addedBy : "Himanshu Patil"
    },
    {
        code :2606,
        coursename : "Databricks",
        department : "DataBricks",
        technology : "React.js",
        duration : "2 weeks",
        modules : 21,
        complexity : "Advance",
        latestModifyBy : "Ishika Jain",
        latestModifyOn : "20/07/2022",
        addedBy : "Nirmal Kukna"
    },
    {
        code :2607,
        coursename : "PMO",
        department : "PMO/QA",
        technology : "Node.js",
        duration : "4 weeks",
        modules : 19,
        complexity : "Advance",
        latestModifyBy : "Himanshi Agrawal",
        latestModifyOn : "10/10/2022",
        addedBy : "Gaurav Sharma"
    },
    {
        code :2608,
        coursename : "Data Cleaning ",
        department : "Data Integartion",
        technology : "React.js",
        duration : "2 weeks",
        modules : 12,
        complexity : "Advance",
        latestModifyBy : "Gunjan Kabra",
        latestModifyOn : "06/10/2022",
        addedBy : "Ishan Jain"
    },
    {
        code :2609,
        coursename : "Chatbot",
        department : "MWP & ChatBot",
        technology : "Node.js",
        duration : "3 weeks",
        modules : 11,
        complexity : "Advance",
        latestModifyBy : "Divya Bhagchandani",
        latestModifyOn : "06/06/2022",
        addedBy : "Anmol Rathore"
    },
    {
        code :2610,
        coursename : "React Advance",
        department : "App Development",
        technology : "React.js",
        duration : "2 weeks",
        modules : 9,
        complexity : "Advance",
        latestModifyBy : "Deepak Wadhwa",
        latestModifyOn : "20/10/2022",
        addedBy : "Himanshu Patil"
    },
    
    {
        code :2630,
        coursename : "UI/UX",
        department : "Power Apps",
        technology : "React.js",
        duration : "2 weeks",
        modules : 25,
        complexity : "Advance",
        latestModifyBy : "Bhavika Chauhan",
        latestModifyOn : "30/07/2022",
        addedBy : "Gaurav Sharma"
    },
    {
        code :2640,
        coursename : ".NET",
        department : "Cloud Infra and security",
        technology : "Node.js",
        duration : "3 weeks",
        modules : 16,
        complexity : "Advance",
        latestModifyBy : "Bhavesh",
        latestModifyOn : "03/01/2022",
        addedBy : "Ishan Jain"
    },
    {
        code :2650,
        coursename : "React Basics",
        department : "Marketing",
        technology : "React.js",
        duration : "2 weeks",
        modules : 22,
        complexity : "Intermediate",
        latestModifyBy : "Rahul Lamba",
        latestModifyOn : "01/12/2022",
        addedBy : "Anmol Rathore"
    },
    {
        code :2660,
        coursename : "React Intermediate",
        department : "PMO",
        technology : "Node.js",
        duration : "4 weeks",
        modules : 12,
        complexity : "Advance",
        latestModifyBy : "Ajay Jangid",
        latestModifyOn : "22/10/2022",
        addedBy : "Himanshu Patil"
    },
    {
        code :2670,
        coursename : "Javascript Advance",
        department : "HR",
        technology : "React.js",
        duration : "2 weeks",
        modules : 13,
        complexity : "Beginner",
        latestModifyBy : "Adhira shashin",
        latestModifyOn : "02/11/2022",
        addedBy : "Nirmal Kukna"
    },
    {
        code :2680,
        coursename : "React.js",
        department : "Busniess Intelligence",
        technology : "Node.js",
        duration : "3 weeks",
        modules : 15,
        complexity : "Advance",
        latestModifyBy : "Abhik swarnakar",
        latestModifyOn : "09/09/2022",
        addedBy : "Gaurav Sharma"
    },
  ]
  export default Data