const unEnrolledListData = [
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
    {
      name: "react",
      duration: "duration",
      complexity: "complexity",
      department: "department",
    },
  ];
  
  export default unEnrolledListData;
  