const completedCourseData = [
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },
  {
    name: "react",
    technology: "technology",
    dateStarted: "dateStarted",
    dateEnded: "dateEnded",
    complexity: "complexity",
    score: "score",
    rank: "rank",
  },

];

export default completedCourseData;
