export const adminActions = {
    GET_COLLEGES: "GET_COLLEGES",
    GET_ALL_LPS: "GET_ALL_LPS",
    GET_CELEBAL_ROLES: "GET_CELEBAL_ROLES",
    GET_COURSES: "GET_COURSES",
    GET_COLLEGE_ROLES: "GET_COLLEGE_ROLES",
    GET_STUDENT_LIST: "GET_STUDENT_LIST",
    GET_STUDENTS_METRICS: "GET_STUDENTS_METRICS",
    GET_ADMIN_METRICS: "GET_ADMIN_METRICS",
    SOCKET_CONNECTION: "SOCKET_CONNECTION",
    COMMUNITY_CHAT: "COMMUNITY_CHAT",
    SOCKET_MESSAGE_OBJ: "SOCKET_MESSAGE_OBJ",
    SET_SELECTED_TAB: "SET_SELECTED_TAB",
    SET_COURSE_DETAIL: "SET_COURSE_DETAIL",
    GET_COLLEGE_ROLE_LIST: "GET_COLLEGE_ROLE_LIST",
    ADMIN_DASHBOARD: "ADMIN_DASHBOARD",
    HR_BUDDY_DASHBOARD: "HRBUDDY_DASHBOARD"
}