export const mentorActions = {
    GET_COURSE_LIST: "GET_COURSE_LIST",
    GET_MENTOR_METRICS: "GET_MENTOR_METRICS",
    GET_COURSE_DETAIL_MENTOR : "GET_COURSE_DETAIL_MENTOR",
    CT_MENTOR_DASHBOARD:"CT_MENTOR_DASHBOARD"
}